name: Daily Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-5'  # 월~금 09:00 KST (00:00 UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          pip install requests beautifulsoup4 feedparser gspread oauth2client schedule playwright
          playwright install
      - run: python full_mystery_automation.py
        env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
